// Code generated by protocol buffer compiler. Do not edit!
package eu.ostrzyciel.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;
import java.io.IOException;

/**
 * Protobuf type {@code RdfDatatypeEntry}
 */
@SuppressWarnings("hiding")
public final class RdfDatatypeEntry extends ProtoMessage<RdfDatatypeEntry> implements Cloneable {
  private static final long serialVersionUID = 0L;

  /**
   * <code>optional uint32 id = 1;</code>
   */
  private int id;

  /**
   * <code>optional string value = 2;</code>
   */
  private String value_ = null;

  private RdfDatatypeEntry() {
  }

  /**
   * @return a new empty instance of {@code RdfDatatypeEntry}
   */
  public static RdfDatatypeEntry newInstance() {
    return new RdfDatatypeEntry();
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return whether the id field is set
   */
  public boolean hasId() {
    return (bitField0_ & 0x00000001) != 0;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return this
   */
  public RdfDatatypeEntry clearId() {
    bitField0_ &= ~0x00000001;
    id = 0;
    return this;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @return the id
   */
  public int getId() {
    return id;
  }

  /**
   * <code>optional uint32 id = 1;</code>
   * @param value the id to set
   * @return this
   */
  public RdfDatatypeEntry setId(final int value) {
    bitField0_ |= 0x00000001;
    id = value;
    return this;
  }

  private void initValue() {
    if (value_ == null) {
      value_ = "";
    }
  }

  /**
   * <code>optional string value = 2;</code>
   * @return whether the value_ field is set
   */
  public boolean hasValue() {
    return (bitField0_ & 0x00000002) != 0;
  }

  /**
   * <code>optional string value = 2;</code>
   * @return this
   */
  public RdfDatatypeEntry clearValue() {
    bitField0_ &= ~0x00000002;
    if (value_ != null) {
      value_ = "";
    }
    return this;
  }

  /**
   * <code>optional string value = 2;</code>
   * @return the value_
   */
  public String getValue() {
    initValue();
    return value_;
  }

  /**
   * <code>optional string value = 2;</code>
   * @param value the value_ to set
   * @return this
   */
  public RdfDatatypeEntry setValue(final String value) {
    initValue();
    bitField0_ |= 0x00000002;
    value_ = value;
    return this;
  }

  @Override
  public RdfDatatypeEntry copyFrom(final RdfDatatypeEntry other) {
    cachedSize = other.cachedSize;
    if ((bitField0_ | other.bitField0_) != 0) {
      bitField0_ = other.bitField0_;
      id = other.id;
      if (other.hasValue()) {
        initValue();
        value_ = other.value_;
      } else {
        clearValue();
      }
    }
    return this;
  }

  @Override
  public RdfDatatypeEntry mergeFrom(final RdfDatatypeEntry other) {
    if (other.isEmpty()) {
      return this;
    }
    cachedSize = -1;
    if (other.hasId()) {
      setId(other.id);
    }
    if (other.hasValue()) {
      value_ = other.value_;
    }
    return this;
  }

  @Override
  public RdfDatatypeEntry clear() {
    if (isEmpty()) {
      return this;
    }
    cachedSize = -1;
    bitField0_ = 0;
    id = 0;
    if (value_ != null) {
      value_ = "";
    }
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfDatatypeEntry)) {
      return false;
    }
    RdfDatatypeEntry other = (RdfDatatypeEntry) o;
    return bitField0_ == other.bitField0_
      && (!hasId() || id == other.id)
      && (!hasValue() || value_.equals(other.value_));
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    if ((bitField0_ & 0x00000001) != 0) {
      output.writeRawByte((byte) 8);
      output.writeUInt32NoTag(id);
    }
    if ((bitField0_ & 0x00000002) != 0) {
      output.writeRawByte((byte) 18);
      output.writeStringNoTag(value_);
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    if ((bitField0_ & 0x00000001) != 0) {
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(id);
    }
    if ((bitField0_ & 0x00000002) != 0) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(value_);
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfDatatypeEntry mergeFrom(final CodedInputStream input) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 8: {
          // id
          id = input.readUInt32();
          bitField0_ |= 0x00000001;
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // value_
          initValue();
          value_ = input.readStringRequireUtf8();
          bitField0_ |= 0x00000002;
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfDatatypeEntry clone() {
    return new RdfDatatypeEntry().copyFrom(this);
  }

  @Override
  public boolean isEmpty() {
    return ((bitField0_) == 0);
  }

  public static RdfDatatypeEntry parseFrom(final byte[] data) throws
      InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfDatatypeEntry(), data).checkInitialized();
  }

  public static RdfDatatypeEntry parseFrom(final CodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfDatatypeEntry(), input).checkInitialized();
  }

  /**
   * @return factory for creating RdfDatatypeEntry messages
   */
  public static MessageFactory<RdfDatatypeEntry> getFactory() {
    return RdfDatatypeEntryFactory.INSTANCE;
  }

  private enum RdfDatatypeEntryFactory implements MessageFactory<RdfDatatypeEntry> {
    INSTANCE;

    @Override
    public RdfDatatypeEntry create() {
      return RdfDatatypeEntry.newInstance();
    }
  }
}
