// Code generated by protocol buffer compiler. Do not edit!
package eu.ostrzyciel.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;
import java.io.IOException;

/**
 * Protobuf type {@code RdfLiteral}
 */
@SuppressWarnings("hiding")
public final class RdfLiteral extends ProtoMessage<RdfLiteral> implements Cloneable {
  /**
   * <code>optional string lex = 1;</code>
   */
  private String lex = null;

  /**
   * <code>optional string langtag = 2;</code>
   */
  private String langtag = null;

  /**
   * <code>optional uint32 datatype = 3;</code>
   */
  private int datatype;

  private RdfLiteral() {
  }

  /**
   * @return a new empty instance of {@code RdfLiteral}
   */
  public static RdfLiteral newInstance() {
    return new RdfLiteral();
  }

  public boolean hasLiteralKind() {
    return true;
  }

  public RdfLiteral clearLiteralKind() {
    if (hasLiteralKind()) {
      clearLangtag();
      clearDatatype();
    }
    return this;
  }

  private void clearLiteralKindOtherLangtag() {
    clearDatatype();
  }

  private void clearLiteralKindOtherDatatype() {
    clearLangtag();
  }

  private void initLex() {
    if (lex == null) {
      lex = "";
    }
  }

  /**
   * <code>optional string lex = 1;</code>
   * @return this
   */
  public RdfLiteral clearLex() {
    if (lex != null) {
      lex = "";
    }
    return this;
  }

  /**
   * <code>optional string lex = 1;</code>
   * @return the lex
   */
  public String getLex() {
    initLex();
    return lex;
  }

  /**
   * <code>optional string lex = 1;</code>
   * @param value the lex to set
   * @return this
   */
  public RdfLiteral setLex(final String value) {
    lex = value;
    return this;
  }

  private void initLangtag() {
    if (langtag == null) {
      langtag = "";
    }
  }

  /**
   * <code>optional string langtag = 2;</code>
   * @return this
   */
  public RdfLiteral clearLangtag() {
    if (langtag != null) {
      langtag = "";
    }
    return this;
  }

  /**
   * <code>optional string langtag = 2;</code>
   * @return the langtag
   */
  public String getLangtag() {
    initLangtag();
    return langtag;
  }

  /**
   * <code>optional string langtag = 2;</code>
   * @param value the langtag to set
   * @return this
   */
  public RdfLiteral setLangtag(final String value) {
    clearLiteralKindOtherLangtag();
    langtag = value;
    return this;
  }

  /**
   * <code>optional uint32 datatype = 3;</code>
   * @return this
   */
  public RdfLiteral clearDatatype() {
    datatype = 0;
    return this;
  }

  /**
   * <code>optional uint32 datatype = 3;</code>
   * @return the datatype
   */
  public int getDatatype() {
    return datatype;
  }

  /**
   * <code>optional uint32 datatype = 3;</code>
   * @param value the datatype to set
   * @return this
   */
  public RdfLiteral setDatatype(final int value) {
    clearLiteralKindOtherDatatype();
    datatype = value;
    return this;
  }

  @Override
  public RdfLiteral copyFrom(final RdfLiteral other) {
    cachedSize = other.cachedSize;
    lex = other.lex;
    langtag = other.langtag;
    datatype = other.datatype;
    return this;
  }

  @Override
  public RdfLiteral mergeFrom(final RdfLiteral other) {
    if (other.isEmpty()) {
      return this;
    }
    cachedSize = -1;
    lex = other.lex;
    langtag = other.langtag;
    setDatatype(other.datatype);
    return this;
  }

  @Override
  public RdfLiteral clear() {
    if (isEmpty()) {
      return this;
    }
    cachedSize = -1;
    if (lex != null) {
      lex = "";
    }
    if (langtag != null) {
      langtag = "";
    }
    datatype = 0;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfLiteral)) {
      return false;
    }
    RdfLiteral other = (RdfLiteral) o;
    return lex.equals(other.lex)
      && langtag.equals(other.langtag)
      && datatype == other.datatype;
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    output.writeRawByte((byte) 10);
    output.writeStringNoTag(lex);
    output.writeRawByte((byte) 18);
    output.writeStringNoTag(langtag);
    output.writeRawByte((byte) 24);
    output.writeUInt32NoTag(datatype);
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    size += 1 + CodedOutputStream.computeStringSizeNoTag(lex);
    size += 1 + CodedOutputStream.computeStringSizeNoTag(langtag);
    size += 1 + CodedOutputStream.computeUInt32SizeNoTag(datatype);
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfLiteral mergeFrom(final CodedInputStream input) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 10: {
          // lex
          initLex();
          lex = input.readStringRequireUtf8();
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // langtag
          clearLiteralKindOtherLangtag();
          initLangtag();
          langtag = input.readStringRequireUtf8();
          tag = input.readTag();
          if (tag != 24) {
            break;
          }
        }
        case 24: {
          // datatype
          clearLiteralKindOtherDatatype();
          datatype = input.readUInt32();
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfLiteral clone() {
    return new RdfLiteral().copyFrom(this);
  }

  public static RdfLiteral parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfLiteral(), data).checkInitialized();
  }

  public static RdfLiteral parseFrom(final CodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfLiteral(), input).checkInitialized();
  }

  /**
   * @return factory for creating RdfLiteral messages
   */
  public static MessageFactory<RdfLiteral> getFactory() {
    return RdfLiteralFactory.INSTANCE;
  }

  private enum RdfLiteralFactory implements MessageFactory<RdfLiteral> {
    INSTANCE;

    @Override
    public RdfLiteral create() {
      return RdfLiteral.newInstance();
    }
  }
}
