// Code generated by protocol buffer compiler. Do not edit!
package eu.ostrzyciel.jelly.core.proto.v1;

import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.InvalidProtocolBufferException;
import eu.neverblink.protoc.java.runtime.MessageFactory;
import eu.neverblink.protoc.java.runtime.ProtoMessage;
import java.io.IOException;

/**
 * Protobuf type {@code RdfTriple}
 */
@SuppressWarnings("hiding")
public final class RdfTriple extends ProtoMessage<RdfTriple> implements Cloneable {
  private static final long serialVersionUID = 0L;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   */
  private RdfIri sIri = null;

  /**
   * <code>optional string s_bnode = 2;</code>
   */
  private String sBnode = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   */
  private RdfLiteral sLiteral = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   */
  private RdfTriple sTripleTerm = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   */
  private RdfIri pIri = null;

  /**
   * <code>optional string p_bnode = 6;</code>
   */
  private String pBnode = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   */
  private RdfLiteral pLiteral = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   */
  private RdfTriple pTripleTerm = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   */
  private RdfIri oIri = null;

  /**
   * <code>optional string o_bnode = 10;</code>
   */
  private String oBnode = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   */
  private RdfLiteral oLiteral = null;

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   */
  private RdfTriple oTripleTerm = null;

  private RdfTriple() {
  }

  /**
   * @return a new empty instance of {@code RdfTriple}
   */
  public static RdfTriple newInstance() {
    return new RdfTriple();
  }

  public boolean hasSubject() {
    return (((bitField0_ & 0x00000f00)) != 0);
  }

  public RdfTriple clearSubject() {
    if (hasSubject()) {
      clearSIri();
      clearSBnode();
      clearSLiteral();
      clearSTripleTerm();
    }
    return this;
  }

  private void clearSubjectOtherSIri() {
    if ((((bitField0_ & 0x00000e00)) != 0)) {
      clearSBnode();
      clearSLiteral();
      clearSTripleTerm();
    }
  }

  private void clearSubjectOtherSBnode() {
    if ((((bitField0_ & 0x00000d00)) != 0)) {
      clearSIri();
      clearSLiteral();
      clearSTripleTerm();
    }
  }

  private void clearSubjectOtherSLiteral() {
    if ((((bitField0_ & 0x00000b00)) != 0)) {
      clearSIri();
      clearSBnode();
      clearSTripleTerm();
    }
  }

  private void clearSubjectOtherSTripleTerm() {
    if ((((bitField0_ & 0x00000700)) != 0)) {
      clearSIri();
      clearSBnode();
      clearSLiteral();
    }
  }

  public boolean hasPredicate() {
    return (((bitField0_ & 0x000000f0)) != 0);
  }

  public RdfTriple clearPredicate() {
    if (hasPredicate()) {
      clearPIri();
      clearPBnode();
      clearPLiteral();
      clearPTripleTerm();
    }
    return this;
  }

  private void clearPredicateOtherPIri() {
    if ((((bitField0_ & 0x000000e0)) != 0)) {
      clearPBnode();
      clearPLiteral();
      clearPTripleTerm();
    }
  }

  private void clearPredicateOtherPBnode() {
    if ((((bitField0_ & 0x000000d0)) != 0)) {
      clearPIri();
      clearPLiteral();
      clearPTripleTerm();
    }
  }

  private void clearPredicateOtherPLiteral() {
    if ((((bitField0_ & 0x000000b0)) != 0)) {
      clearPIri();
      clearPBnode();
      clearPTripleTerm();
    }
  }

  private void clearPredicateOtherPTripleTerm() {
    if ((((bitField0_ & 0x00000070)) != 0)) {
      clearPIri();
      clearPBnode();
      clearPLiteral();
    }
  }

  public boolean hasObject() {
    return (((bitField0_ & 0x0000000f)) != 0);
  }

  public RdfTriple clearObject() {
    if (hasObject()) {
      clearOIri();
      clearOBnode();
      clearOLiteral();
      clearOTripleTerm();
    }
    return this;
  }

  private void clearObjectOtherOIri() {
    if ((((bitField0_ & 0x0000000e)) != 0)) {
      clearOBnode();
      clearOLiteral();
      clearOTripleTerm();
    }
  }

  private void clearObjectOtherOBnode() {
    if ((((bitField0_ & 0x0000000d)) != 0)) {
      clearOIri();
      clearOLiteral();
      clearOTripleTerm();
    }
  }

  private void clearObjectOtherOLiteral() {
    if ((((bitField0_ & 0x0000000b)) != 0)) {
      clearOIri();
      clearOBnode();
      clearOTripleTerm();
    }
  }

  private void clearObjectOtherOTripleTerm() {
    if ((((bitField0_ & 0x00000007)) != 0)) {
      clearOIri();
      clearOBnode();
      clearOLiteral();
    }
  }

  private void initSIri() {
    if (sIri == null) {
      sIri = RdfIri.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   * @return whether the sIri field is set
   */
  public boolean hasSIri() {
    return (bitField0_ & 0x00000100) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   * @return this
   */
  public RdfTriple clearSIri() {
    bitField0_ &= ~0x00000100;
    if (sIri != null) {
      sIri.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableSIri()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfIri getSIri() {
    initSIri();
    return sIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfIri getMutableSIri() {
    clearSubjectOtherSIri();
    initSIri();
    bitField0_ |= 0x00000100;
    return sIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri s_iri = 1;</code>
   * @param value the sIri to set
   * @return this
   */
  public RdfTriple setSIri(final RdfIri value) {
    clearSubjectOtherSIri();
    initSIri();
    bitField0_ |= 0x00000100;
    sIri.copyFrom(value);
    return this;
  }

  private void initSBnode() {
    if (sBnode == null) {
      sBnode = "";
    }
  }

  /**
   * <code>optional string s_bnode = 2;</code>
   * @return whether the sBnode field is set
   */
  public boolean hasSBnode() {
    return (bitField0_ & 0x00000200) != 0;
  }

  /**
   * <code>optional string s_bnode = 2;</code>
   * @return this
   */
  public RdfTriple clearSBnode() {
    bitField0_ &= ~0x00000200;
    if (sBnode != null) {
      sBnode = "";
    }
    return this;
  }

  /**
   * <code>optional string s_bnode = 2;</code>
   * @return the sBnode
   */
  public String getSBnode() {
    initSBnode();
    return sBnode;
  }

  /**
   * <code>optional string s_bnode = 2;</code>
   * @param value the sBnode to set
   * @return this
   */
  public RdfTriple setSBnode(final String value) {
    clearSubjectOtherSBnode();
    initSBnode();
    bitField0_ |= 0x00000200;
    sBnode = value;
    return this;
  }

  private void initSLiteral() {
    if (sLiteral == null) {
      sLiteral = RdfLiteral.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   * @return whether the sLiteral field is set
   */
  public boolean hasSLiteral() {
    return (bitField0_ & 0x00000400) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   * @return this
   */
  public RdfTriple clearSLiteral() {
    bitField0_ &= ~0x00000400;
    if (sLiteral != null) {
      sLiteral.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableSLiteral()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfLiteral getSLiteral() {
    initSLiteral();
    return sLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfLiteral getMutableSLiteral() {
    clearSubjectOtherSLiteral();
    initSLiteral();
    bitField0_ |= 0x00000400;
    return sLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral s_literal = 3;</code>
   * @param value the sLiteral to set
   * @return this
   */
  public RdfTriple setSLiteral(final RdfLiteral value) {
    clearSubjectOtherSLiteral();
    initSLiteral();
    bitField0_ |= 0x00000400;
    sLiteral.copyFrom(value);
    return this;
  }

  private void initSTripleTerm() {
    if (sTripleTerm == null) {
      sTripleTerm = RdfTriple.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   * @return whether the sTripleTerm field is set
   */
  public boolean hasSTripleTerm() {
    return (bitField0_ & 0x00000800) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   * @return this
   */
  public RdfTriple clearSTripleTerm() {
    bitField0_ &= ~0x00000800;
    if (sTripleTerm != null) {
      sTripleTerm.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableSTripleTerm()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfTriple getSTripleTerm() {
    initSTripleTerm();
    return sTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfTriple getMutableSTripleTerm() {
    clearSubjectOtherSTripleTerm();
    initSTripleTerm();
    bitField0_ |= 0x00000800;
    return sTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple s_triple_term = 4;</code>
   * @param value the sTripleTerm to set
   * @return this
   */
  public RdfTriple setSTripleTerm(final RdfTriple value) {
    clearSubjectOtherSTripleTerm();
    initSTripleTerm();
    bitField0_ |= 0x00000800;
    sTripleTerm.copyFrom(value);
    return this;
  }

  private void initPIri() {
    if (pIri == null) {
      pIri = RdfIri.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   * @return whether the pIri field is set
   */
  public boolean hasPIri() {
    return (bitField0_ & 0x00000010) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   * @return this
   */
  public RdfTriple clearPIri() {
    bitField0_ &= ~0x00000010;
    if (pIri != null) {
      pIri.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutablePIri()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfIri getPIri() {
    initPIri();
    return pIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfIri getMutablePIri() {
    clearPredicateOtherPIri();
    initPIri();
    bitField0_ |= 0x00000010;
    return pIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri p_iri = 5;</code>
   * @param value the pIri to set
   * @return this
   */
  public RdfTriple setPIri(final RdfIri value) {
    clearPredicateOtherPIri();
    initPIri();
    bitField0_ |= 0x00000010;
    pIri.copyFrom(value);
    return this;
  }

  private void initPBnode() {
    if (pBnode == null) {
      pBnode = "";
    }
  }

  /**
   * <code>optional string p_bnode = 6;</code>
   * @return whether the pBnode field is set
   */
  public boolean hasPBnode() {
    return (bitField0_ & 0x00000020) != 0;
  }

  /**
   * <code>optional string p_bnode = 6;</code>
   * @return this
   */
  public RdfTriple clearPBnode() {
    bitField0_ &= ~0x00000020;
    if (pBnode != null) {
      pBnode = "";
    }
    return this;
  }

  /**
   * <code>optional string p_bnode = 6;</code>
   * @return the pBnode
   */
  public String getPBnode() {
    initPBnode();
    return pBnode;
  }

  /**
   * <code>optional string p_bnode = 6;</code>
   * @param value the pBnode to set
   * @return this
   */
  public RdfTriple setPBnode(final String value) {
    clearPredicateOtherPBnode();
    initPBnode();
    bitField0_ |= 0x00000020;
    pBnode = value;
    return this;
  }

  private void initPLiteral() {
    if (pLiteral == null) {
      pLiteral = RdfLiteral.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   * @return whether the pLiteral field is set
   */
  public boolean hasPLiteral() {
    return (bitField0_ & 0x00000040) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   * @return this
   */
  public RdfTriple clearPLiteral() {
    bitField0_ &= ~0x00000040;
    if (pLiteral != null) {
      pLiteral.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutablePLiteral()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfLiteral getPLiteral() {
    initPLiteral();
    return pLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfLiteral getMutablePLiteral() {
    clearPredicateOtherPLiteral();
    initPLiteral();
    bitField0_ |= 0x00000040;
    return pLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral p_literal = 7;</code>
   * @param value the pLiteral to set
   * @return this
   */
  public RdfTriple setPLiteral(final RdfLiteral value) {
    clearPredicateOtherPLiteral();
    initPLiteral();
    bitField0_ |= 0x00000040;
    pLiteral.copyFrom(value);
    return this;
  }

  private void initPTripleTerm() {
    if (pTripleTerm == null) {
      pTripleTerm = RdfTriple.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   * @return whether the pTripleTerm field is set
   */
  public boolean hasPTripleTerm() {
    return (bitField0_ & 0x00000080) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   * @return this
   */
  public RdfTriple clearPTripleTerm() {
    bitField0_ &= ~0x00000080;
    if (pTripleTerm != null) {
      pTripleTerm.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutablePTripleTerm()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfTriple getPTripleTerm() {
    initPTripleTerm();
    return pTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfTriple getMutablePTripleTerm() {
    clearPredicateOtherPTripleTerm();
    initPTripleTerm();
    bitField0_ |= 0x00000080;
    return pTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple p_triple_term = 8;</code>
   * @param value the pTripleTerm to set
   * @return this
   */
  public RdfTriple setPTripleTerm(final RdfTriple value) {
    clearPredicateOtherPTripleTerm();
    initPTripleTerm();
    bitField0_ |= 0x00000080;
    pTripleTerm.copyFrom(value);
    return this;
  }

  private void initOIri() {
    if (oIri == null) {
      oIri = RdfIri.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   * @return whether the oIri field is set
   */
  public boolean hasOIri() {
    return (bitField0_ & 0x00000001) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   * @return this
   */
  public RdfTriple clearOIri() {
    bitField0_ &= ~0x00000001;
    if (oIri != null) {
      oIri.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableOIri()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfIri getOIri() {
    initOIri();
    return oIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfIri getMutableOIri() {
    clearObjectOtherOIri();
    initOIri();
    bitField0_ |= 0x00000001;
    return oIri;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfIri o_iri = 9;</code>
   * @param value the oIri to set
   * @return this
   */
  public RdfTriple setOIri(final RdfIri value) {
    clearObjectOtherOIri();
    initOIri();
    bitField0_ |= 0x00000001;
    oIri.copyFrom(value);
    return this;
  }

  private void initOBnode() {
    if (oBnode == null) {
      oBnode = "";
    }
  }

  /**
   * <code>optional string o_bnode = 10;</code>
   * @return whether the oBnode field is set
   */
  public boolean hasOBnode() {
    return (bitField0_ & 0x00000002) != 0;
  }

  /**
   * <code>optional string o_bnode = 10;</code>
   * @return this
   */
  public RdfTriple clearOBnode() {
    bitField0_ &= ~0x00000002;
    if (oBnode != null) {
      oBnode = "";
    }
    return this;
  }

  /**
   * <code>optional string o_bnode = 10;</code>
   * @return the oBnode
   */
  public String getOBnode() {
    initOBnode();
    return oBnode;
  }

  /**
   * <code>optional string o_bnode = 10;</code>
   * @param value the oBnode to set
   * @return this
   */
  public RdfTriple setOBnode(final String value) {
    clearObjectOtherOBnode();
    initOBnode();
    bitField0_ |= 0x00000002;
    oBnode = value;
    return this;
  }

  private void initOLiteral() {
    if (oLiteral == null) {
      oLiteral = RdfLiteral.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   * @return whether the oLiteral field is set
   */
  public boolean hasOLiteral() {
    return (bitField0_ & 0x00000004) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   * @return this
   */
  public RdfTriple clearOLiteral() {
    bitField0_ &= ~0x00000004;
    if (oLiteral != null) {
      oLiteral.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableOLiteral()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfLiteral getOLiteral() {
    initOLiteral();
    return oLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfLiteral getMutableOLiteral() {
    clearObjectOtherOLiteral();
    initOLiteral();
    bitField0_ |= 0x00000004;
    return oLiteral;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfLiteral o_literal = 11;</code>
   * @param value the oLiteral to set
   * @return this
   */
  public RdfTriple setOLiteral(final RdfLiteral value) {
    clearObjectOtherOLiteral();
    initOLiteral();
    bitField0_ |= 0x00000004;
    oLiteral.copyFrom(value);
    return this;
  }

  private void initOTripleTerm() {
    if (oTripleTerm == null) {
      oTripleTerm = RdfTriple.newInstance();
    }
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   * @return whether the oTripleTerm field is set
   */
  public boolean hasOTripleTerm() {
    return (bitField0_ & 0x00000008) != 0;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   * @return this
   */
  public RdfTriple clearOTripleTerm() {
    bitField0_ &= ~0x00000008;
    if (oTripleTerm != null) {
      oTripleTerm.clear();
    }
    return this;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   *
   * This method returns the internal storage object without modifying any has state.
   * The returned object should not be modified and be treated as read-only.
   *
   * Use {@link #getMutableOTripleTerm()} if you want to modify it.
   *
   * @return internal storage object for reading
   */
  public RdfTriple getOTripleTerm() {
    initOTripleTerm();
    return oTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   *
   * This method returns the internal storage object and sets the corresponding
   * has state. The returned object will become part of this message and its
   * contents may be modified as long as the has state is not cleared.
   *
   * @return internal storage object for modifications
   */
  public RdfTriple getMutableOTripleTerm() {
    clearObjectOtherOTripleTerm();
    initOTripleTerm();
    bitField0_ |= 0x00000008;
    return oTripleTerm;
  }

  /**
   * <code>optional .eu.ostrzyciel.jelly.core.proto.v1.RdfTriple o_triple_term = 12;</code>
   * @param value the oTripleTerm to set
   * @return this
   */
  public RdfTriple setOTripleTerm(final RdfTriple value) {
    clearObjectOtherOTripleTerm();
    initOTripleTerm();
    bitField0_ |= 0x00000008;
    oTripleTerm.copyFrom(value);
    return this;
  }

  @Override
  public RdfTriple copyFrom(final RdfTriple other) {
    cachedSize = other.cachedSize;
    if ((bitField0_ | other.bitField0_) != 0) {
      bitField0_ = other.bitField0_;
      if (other.hasSIri()) {
        initSIri();
        sIri.copyFrom(other.sIri);
      } else {
        clearSIri();
      }
      if (other.hasSBnode()) {
        initSBnode();
        sBnode = other.sBnode;
      } else {
        clearSBnode();
      }
      if (other.hasSLiteral()) {
        initSLiteral();
        sLiteral.copyFrom(other.sLiteral);
      } else {
        clearSLiteral();
      }
      if (other.hasSTripleTerm()) {
        initSTripleTerm();
        sTripleTerm.copyFrom(other.sTripleTerm);
      } else {
        clearSTripleTerm();
      }
      if (other.hasPIri()) {
        initPIri();
        pIri.copyFrom(other.pIri);
      } else {
        clearPIri();
      }
      if (other.hasPBnode()) {
        initPBnode();
        pBnode = other.pBnode;
      } else {
        clearPBnode();
      }
      if (other.hasPLiteral()) {
        initPLiteral();
        pLiteral.copyFrom(other.pLiteral);
      } else {
        clearPLiteral();
      }
      if (other.hasPTripleTerm()) {
        initPTripleTerm();
        pTripleTerm.copyFrom(other.pTripleTerm);
      } else {
        clearPTripleTerm();
      }
      if (other.hasOIri()) {
        initOIri();
        oIri.copyFrom(other.oIri);
      } else {
        clearOIri();
      }
      if (other.hasOBnode()) {
        initOBnode();
        oBnode = other.oBnode;
      } else {
        clearOBnode();
      }
      if (other.hasOLiteral()) {
        initOLiteral();
        oLiteral.copyFrom(other.oLiteral);
      } else {
        clearOLiteral();
      }
      if (other.hasOTripleTerm()) {
        initOTripleTerm();
        oTripleTerm.copyFrom(other.oTripleTerm);
      } else {
        clearOTripleTerm();
      }
    }
    return this;
  }

  @Override
  public RdfTriple mergeFrom(final RdfTriple other) {
    if (other.isEmpty()) {
      return this;
    }
    cachedSize = -1;
    if (other.hasSIri()) {
      getMutableSIri().mergeFrom(other.sIri);
    }
    if (other.hasSBnode()) {
      sBnode = other.sBnode;
    }
    if (other.hasSLiteral()) {
      getMutableSLiteral().mergeFrom(other.sLiteral);
    }
    if (other.hasSTripleTerm()) {
      getMutableSTripleTerm().mergeFrom(other.sTripleTerm);
    }
    if (other.hasPIri()) {
      getMutablePIri().mergeFrom(other.pIri);
    }
    if (other.hasPBnode()) {
      pBnode = other.pBnode;
    }
    if (other.hasPLiteral()) {
      getMutablePLiteral().mergeFrom(other.pLiteral);
    }
    if (other.hasPTripleTerm()) {
      getMutablePTripleTerm().mergeFrom(other.pTripleTerm);
    }
    if (other.hasOIri()) {
      getMutableOIri().mergeFrom(other.oIri);
    }
    if (other.hasOBnode()) {
      oBnode = other.oBnode;
    }
    if (other.hasOLiteral()) {
      getMutableOLiteral().mergeFrom(other.oLiteral);
    }
    if (other.hasOTripleTerm()) {
      getMutableOTripleTerm().mergeFrom(other.oTripleTerm);
    }
    return this;
  }

  @Override
  public RdfTriple clear() {
    if (isEmpty()) {
      return this;
    }
    cachedSize = -1;
    bitField0_ = 0;
    if (sIri != null) {
      sIri.clear();
    }
    if (sBnode != null) {
      sBnode = "";
    }
    if (sLiteral != null) {
      sLiteral.clear();
    }
    if (sTripleTerm != null) {
      sTripleTerm.clear();
    }
    if (pIri != null) {
      pIri.clear();
    }
    if (pBnode != null) {
      pBnode = "";
    }
    if (pLiteral != null) {
      pLiteral.clear();
    }
    if (pTripleTerm != null) {
      pTripleTerm.clear();
    }
    if (oIri != null) {
      oIri.clear();
    }
    if (oBnode != null) {
      oBnode = "";
    }
    if (oLiteral != null) {
      oLiteral.clear();
    }
    if (oTripleTerm != null) {
      oTripleTerm.clear();
    }
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (!(o instanceof RdfTriple)) {
      return false;
    }
    RdfTriple other = (RdfTriple) o;
    return bitField0_ == other.bitField0_
      && (!hasSIri() || sIri.equals(other.sIri))
      && (!hasSBnode() || sBnode.equals(other.sBnode))
      && (!hasSLiteral() || sLiteral.equals(other.sLiteral))
      && (!hasSTripleTerm() || sTripleTerm.equals(other.sTripleTerm))
      && (!hasPIri() || pIri.equals(other.pIri))
      && (!hasPBnode() || pBnode.equals(other.pBnode))
      && (!hasPLiteral() || pLiteral.equals(other.pLiteral))
      && (!hasPTripleTerm() || pTripleTerm.equals(other.pTripleTerm))
      && (!hasOIri() || oIri.equals(other.oIri))
      && (!hasOBnode() || oBnode.equals(other.oBnode))
      && (!hasOLiteral() || oLiteral.equals(other.oLiteral))
      && (!hasOTripleTerm() || oTripleTerm.equals(other.oTripleTerm));
  }

  @Override
  public void writeTo(final CodedOutputStream output) throws IOException {
    if ((bitField0_ & 0x00000100) != 0) {
      output.writeRawByte((byte) 10);
      output.writeUInt32NoTag(sIri.getCachedSize());
      sIri.writeTo(output);
    }
    if ((bitField0_ & 0x00000200) != 0) {
      output.writeRawByte((byte) 18);
      output.writeStringNoTag(sBnode);
    }
    if ((bitField0_ & 0x00000400) != 0) {
      output.writeRawByte((byte) 26);
      output.writeUInt32NoTag(sLiteral.getCachedSize());
      sLiteral.writeTo(output);
    }
    if ((bitField0_ & 0x00000800) != 0) {
      output.writeRawByte((byte) 34);
      output.writeUInt32NoTag(sTripleTerm.getCachedSize());
      sTripleTerm.writeTo(output);
    }
    if ((bitField0_ & 0x00000010) != 0) {
      output.writeRawByte((byte) 42);
      output.writeUInt32NoTag(pIri.getCachedSize());
      pIri.writeTo(output);
    }
    if ((bitField0_ & 0x00000020) != 0) {
      output.writeRawByte((byte) 50);
      output.writeStringNoTag(pBnode);
    }
    if ((bitField0_ & 0x00000040) != 0) {
      output.writeRawByte((byte) 58);
      output.writeUInt32NoTag(pLiteral.getCachedSize());
      pLiteral.writeTo(output);
    }
    if ((bitField0_ & 0x00000080) != 0) {
      output.writeRawByte((byte) 66);
      output.writeUInt32NoTag(pTripleTerm.getCachedSize());
      pTripleTerm.writeTo(output);
    }
    if ((bitField0_ & 0x00000001) != 0) {
      output.writeRawByte((byte) 74);
      output.writeUInt32NoTag(oIri.getCachedSize());
      oIri.writeTo(output);
    }
    if ((bitField0_ & 0x00000002) != 0) {
      output.writeRawByte((byte) 82);
      output.writeStringNoTag(oBnode);
    }
    if ((bitField0_ & 0x00000004) != 0) {
      output.writeRawByte((byte) 90);
      output.writeUInt32NoTag(oLiteral.getCachedSize());
      oLiteral.writeTo(output);
    }
    if ((bitField0_ & 0x00000008) != 0) {
      output.writeRawByte((byte) 98);
      output.writeUInt32NoTag(oTripleTerm.getCachedSize());
      oTripleTerm.writeTo(output);
    }
  }

  @Override
  protected int computeSerializedSize() {
    int size = 0;
    if ((bitField0_ & 0x00000100) != 0) {
      final int dataSize = sIri.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000200) != 0) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(sBnode);
    }
    if ((bitField0_ & 0x00000400) != 0) {
      final int dataSize = sLiteral.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000800) != 0) {
      final int dataSize = sTripleTerm.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000010) != 0) {
      final int dataSize = pIri.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000020) != 0) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(pBnode);
    }
    if ((bitField0_ & 0x00000040) != 0) {
      final int dataSize = pLiteral.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000080) != 0) {
      final int dataSize = pTripleTerm.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000001) != 0) {
      final int dataSize = oIri.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000002) != 0) {
      size += 1 + CodedOutputStream.computeStringSizeNoTag(oBnode);
    }
    if ((bitField0_ & 0x00000004) != 0) {
      final int dataSize = oLiteral.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    if ((bitField0_ & 0x00000008) != 0) {
      final int dataSize = oTripleTerm.getSerializedSize();
      size += 1 + CodedOutputStream.computeUInt32SizeNoTag(dataSize) + dataSize;
    }
    return size;
  }

  @Override
  @SuppressWarnings("fallthrough")
  public RdfTriple mergeFrom(final CodedInputStream input) throws IOException {
    // Enabled Fall-Through Optimization (Quickbuf)
    int tag = input.readTag();
    while (true) {
      switch (tag) {
        case 10: {
          // sIri
          clearSubjectOtherSIri();
          initSIri();
          ProtoMessage.mergeDelimitedFrom(sIri, input);
          bitField0_ |= 0x00000100;
          tag = input.readTag();
          if (tag != 18) {
            break;
          }
        }
        case 18: {
          // sBnode
          clearSubjectOtherSBnode();
          initSBnode();
          sBnode = input.readStringRequireUtf8();
          bitField0_ |= 0x00000200;
          tag = input.readTag();
          if (tag != 26) {
            break;
          }
        }
        case 26: {
          // sLiteral
          clearSubjectOtherSLiteral();
          initSLiteral();
          ProtoMessage.mergeDelimitedFrom(sLiteral, input);
          bitField0_ |= 0x00000400;
          tag = input.readTag();
          if (tag != 34) {
            break;
          }
        }
        case 34: {
          // sTripleTerm
          clearSubjectOtherSTripleTerm();
          initSTripleTerm();
          ProtoMessage.mergeDelimitedFrom(sTripleTerm, input);
          bitField0_ |= 0x00000800;
          tag = input.readTag();
          if (tag != 42) {
            break;
          }
        }
        case 42: {
          // pIri
          clearPredicateOtherPIri();
          initPIri();
          ProtoMessage.mergeDelimitedFrom(pIri, input);
          bitField0_ |= 0x00000010;
          tag = input.readTag();
          if (tag != 50) {
            break;
          }
        }
        case 50: {
          // pBnode
          clearPredicateOtherPBnode();
          initPBnode();
          pBnode = input.readStringRequireUtf8();
          bitField0_ |= 0x00000020;
          tag = input.readTag();
          if (tag != 58) {
            break;
          }
        }
        case 58: {
          // pLiteral
          clearPredicateOtherPLiteral();
          initPLiteral();
          ProtoMessage.mergeDelimitedFrom(pLiteral, input);
          bitField0_ |= 0x00000040;
          tag = input.readTag();
          if (tag != 66) {
            break;
          }
        }
        case 66: {
          // pTripleTerm
          clearPredicateOtherPTripleTerm();
          initPTripleTerm();
          ProtoMessage.mergeDelimitedFrom(pTripleTerm, input);
          bitField0_ |= 0x00000080;
          tag = input.readTag();
          if (tag != 74) {
            break;
          }
        }
        case 74: {
          // oIri
          clearObjectOtherOIri();
          initOIri();
          ProtoMessage.mergeDelimitedFrom(oIri, input);
          bitField0_ |= 0x00000001;
          tag = input.readTag();
          if (tag != 82) {
            break;
          }
        }
        case 82: {
          // oBnode
          clearObjectOtherOBnode();
          initOBnode();
          oBnode = input.readStringRequireUtf8();
          bitField0_ |= 0x00000002;
          tag = input.readTag();
          if (tag != 90) {
            break;
          }
        }
        case 90: {
          // oLiteral
          clearObjectOtherOLiteral();
          initOLiteral();
          ProtoMessage.mergeDelimitedFrom(oLiteral, input);
          bitField0_ |= 0x00000004;
          tag = input.readTag();
          if (tag != 98) {
            break;
          }
        }
        case 98: {
          // oTripleTerm
          clearObjectOtherOTripleTerm();
          initOTripleTerm();
          ProtoMessage.mergeDelimitedFrom(oTripleTerm, input);
          bitField0_ |= 0x00000008;
          tag = input.readTag();
          if (tag != 0) {
            break;
          }
        }
        case 0: {
          return this;
        }
        default: {
          if (!input.skipField(tag)) {
            return this;
          }
          tag = input.readTag();
          break;
        }
      }
    }
  }

  @Override
  public RdfTriple clone() {
    return new RdfTriple().copyFrom(this);
  }

  @Override
  public boolean isEmpty() {
    return ((bitField0_) == 0);
  }

  public static RdfTriple parseFrom(final byte[] data) throws InvalidProtocolBufferException {
    return ProtoMessage.mergeFrom(new RdfTriple(), data).checkInitialized();
  }

  public static RdfTriple parseFrom(final CodedInputStream input) throws IOException {
    return ProtoMessage.mergeFrom(new RdfTriple(), input).checkInitialized();
  }

  /**
   * @return factory for creating RdfTriple messages
   */
  public static MessageFactory<RdfTriple> getFactory() {
    return RdfTripleFactory.INSTANCE;
  }

  private enum RdfTripleFactory implements MessageFactory<RdfTriple> {
    INSTANCE;

    @Override
    public RdfTriple create() {
      return RdfTriple.newInstance();
    }
  }
}
